version: '3'
services:
  my_container:
    image: dockercloud/hello-world:latest
    networks:
      - reseau1
  load-balancer:
    image: dockercloud/haproxy:latest
    depends_on:
      - my_container
    ports:
      - "8080:80"
    links:
      - my_container
    networks:
      - reseau1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
networks:
  reseau1: